In [18]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("/Users/jballesteros/Documents/git/uchicago-mpp/4_autumn_2026/investments/pset_2/ps2_problem1-1.xlsx")

In [3]:
df.head()

  Calendar Date    Market    Target     Tesla  Alphabet
0    2010-07-30  0.070360  0.043726 -0.163240  0.089673
1    2010-08-31 -0.042863  0.001680 -0.023069 -0.071837
2    2010-09-30  0.091628  0.044566  0.047485  0.168370
3    2010-10-29  0.038591 -0.028069  0.070326  0.167196
4    2010-11-30  0.005117  0.101192  0.617674 -0.094492

## (a) Find the average returns on the Market and each of the three stocks over the entire period from July 30, 2010 through the end of 2025

In [6]:
df.describe()

,Calendar Date,Market,Target,Tesla,Alphabet
count,186,186.000000,186.000000,186.000000,186.000000
mean,2018-04-15 06:19:21.290322688,0.011483,0.009103,0.045293,0.020687
min,2010-07-30 00:00:00,-0.141733,-0.289059,-0.367334,-0.179467
25%,2014-06-06 18:00:00,-0.013140,-0.037284,-0.072731,-0.025029
50%,2018-04-14 00:00:00,0.014639,0.004889,0.011737,0.019609
75%,2022-02-21 00:00:00,0.035221,0.048733,0.127312,0.068246
max,2025-12-31 00:00:00,0.129674,0.248449,0.810706,0.217502
std,NaN,0.041830,0.078560,0.181656,0.072228

## (b) Find the variance of each of these returns over the entire period.

In [8]:
df["Market"].var()

np.float64(0.0017497599509069457)

In [9]:
df["Target"].var()

np.float64(0.006171721741234177)

In [10]:
df["Tesla"].var()

np.float64(0.032998866510785936)

In [11]:
df["Alphabet"].var()

np.float64(0.005216937125726503)

In [13]:
rets = df.set_index("Calendar Date")

Market      0.011483
Target      0.009103
Tesla       0.045293
Alphabet    0.020687
dtype: float64

In [16]:
rets.mean()

Market      0.011483
Target      0.009103
Tesla       0.045293
Alphabet    0.020687
dtype: float64

In [14]:
rets.var()

Market      0.001750
Target      0.006172
Tesla       0.032999
Alphabet    0.005217
dtype: float64

In [17]:
rets.cov()

            Market    Target     Tesla  Alphabet
Market    0.001750  0.001556  0.002871  0.001728
Target    0.001556  0.006172  0.002829  0.001314
Tesla     0.002871  0.002829  0.032999  0.003194
Alphabet  0.001728  0.001314  0.003194  0.005217

## (d) Consider the following two portfolios:

Portfolio A had 60% invested in Target, 20% in Tesla and 20% in Alphabet at the beginning of each month.

Portfolio B had 60% invested in Tesla, 20% in Target and 20% in Alphabet at the beginning of each month.

In [30]:
stocks = ["Target", "Tesla", "Alphabet"]
a = np.array([0.6, 0.2, 0.2])
b = np.array([0.2, 0.6, 0.2])
mu = rets[stocks].mean().values.round(4)
S = rets[stocks].cov().values.round(4)

Using just the average returns and variances of the three stocks, plus the covariances between the stocks (calculated in parts a, b and c), calculate the average returns and variances of these two portfolios, and the covariance between the two portfolios.

In [35]:
# average returns
a @ mu

np.float64(0.018660000000000003)

In [36]:
b @ mu

np.float64(0.033139999999999996)

In [32]:
# variance
a @ S @ a

np.float64(0.005)

In [37]:
b @ S @ b

np.float64(0.01388)

In [33]:
# covariance
a @ S @ b

np.float64(0.006752)

Now on a spreadsheet calculate the realized returns of each of the portfolios for each month. Using these realized returns calculate the portfolio average returns, variances and the covariance directly, confirming your answers from above.

In [38]:
rA = rets[stocks] @ a
rB = rets[stocks] @ b

In [43]:
rA.mean().round(4)

np.float64(0.0187)

In [47]:
rB.mean().round(4)

np.float64(0.0331)

In [44]:
rA.var().round(4)

np.float64(0.005)

In [48]:
rB.var().round(4)

np.float64(0.0139)

In [46]:
rA.cov(rB).round(4)

np.float64(0.0068)